CREATE TABLE IF NOT EXISTS tasks (
	id CHAR(36) NOT NULL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	description TEXT,
	is_done BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP,
	updated_at TIMESTAMP
);
